// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function GetConfig():Promise<main.ConfigData>;

export function GetHistory(arg1:number):Promise<Array<main.Message>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InvokeAgent(arg1:string,arg2:string,arg3:Record<string, any>):Promise<any>;

export function ListAgents():Promise<Array<string>>;

export function ListModels():Promise<Array<main.ModelInfo>>;

export function LoadModel(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.ConfigData):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UnloadModel(arg1:string):Promise<void>;
